# Understanding The Workflow File
# https://docs.github.com/en/actions/using-workflows/about-workflows#understanding-the-workflow-file

name: "Continuous Integration (CI)"
on: ["push", "pull_request"]

jobs:
  code-analysis:
    name: "Code Analysis"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version: "1.18.3"
      - name: Run unit tests
        run: go test -race -covermode=atomic -coverprofile=coverage.out ./...
      - name: Print env variables
        run: printenv
      - uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: "2022.1.3"
          install-go: false
          cache-key: "1.18.3"
      - name: Sonarcloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  vulns-scanner:
    name: Vulnerability Scanner
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/google/osv-scanner:latest
      volumes:
        - ./:/github/workspace
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run OSV scanner
        run: /osv-scanner -r /github/workspace
